name: Test
on: [push]
jobs:
  build_rails:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: '2.6'
            rails-version: '5.2'
          - ruby-version: '2.7'
            rails-version: '6.0'
          - ruby-version: '2.7'
            rails-version: '6.1'
          - ruby-version: '3.1'
            rails-version: '7.0'
          - ruby-version: '3.2'
            rails-version: '7.1'
          - ruby-version: '3.3'
            rails-version: '7.2'
          - ruby-version: '3.4'
            rails-version: '8.0'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile
      - name: Run Rails Tests
        run: bundle exec rake spec:rails && bundle exec rake spec:rails
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile

  build_ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: '2.6'
          - ruby-version: '2.7'
          - ruby-version: '3.0'
          - ruby-version: '3.1'
          - ruby-version: '3.2'
          - ruby-version: '3.3'
          - ruby-version: '3.4'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/ruby.gemfile
      - name: Run Ruby Tests
        run: bundle exec rake spec:ruby
        env:
          BUNDLE_GEMFILE: gemfiles/ruby.gemfile